<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link rel="stylesheet" href="/css/addCodePage-style.css">
    <script type="text/javascript" src="/js/script.js"></script>
</head>
<body>
    <textarea id="code_snippet" placeholder="// write your code here" cols=5 rows=3></textarea>
    <p>Time restriction: </p>
    <input id="time_restriction" type="text">
    <p>Views restriction: </p>
    <input id="views_restriction" type="text"/>
    <button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>

</html>